@startuml 01_alta_jugador
title Alta de jugador

actor "Vista" as V
participant "JugadorController" as JC
participant "Jugador" as J
participant "JugadorService" as JS
participant "JugadorDAO" as JD

V -> JC : nuevoJugador(nombre, mail)
activate JC

JC -> J ** : new Jugador(nombre, mail, 0)
activate J
J --> JC : jugador
deactivate J

JC -> JS : guardarJugador(jugador)
activate JS

JS -> JD : crearJugador(jugador)
activate JD
note right of JD
  Persiste el jugador en la DB
  (transaccion JPA encapsulada)
end note
JD --> JS
deactivate JD

JS --> JC
deactivate JS

JC --> V
deactivate JC

@enduml
